# Generated by Django 2.1.10 on 2020-06-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='主机名称')),
                ('ip', models.GenericIPAddressField(verbose_name='主机ip地址')),
            ],
        ),
    ]
